/*
 * JDialogAfficheFourier.java
 *
 * Created on 9 août 2007, 9:23
 */

package isilimageprocessing.Dialogues;

import CImage.CImageNG;
import CImage.Exceptions.CImageNGException;
import CImage.Observers.JLabelBeanCImage;

import javax.swing.*;

/**
 *
 * @author  HP_Propriétaire
 */
public class JDialogAfficheFiltre extends JDialog
{
    private double   matrice[][];
    private int      M,N;
    private CImageNG image;
    private int      matrice_int[][];
    
    private JLabelBeanCImage observer;
    
    /** Creates new form JDialogAfficheFourier */
    public JDialogAfficheFiltre(java.awt.Frame parent, boolean modal, double m[][], String titre)
    {
        super(parent, modal);
        initComponents();
        setTitle(titre);
        
        matrice = m;
        M = matrice.length;
        N = matrice[0].length;
        matrice_int = new int[M][N];
        try 
        {
            image = new CImageNG(M,N,0);
        } 
        catch (CImageNGException ex) 
        { System.out.println("Erreur CImageNG : " + ex.getMessage()); }
        
        observer = new JLabelBeanCImage(image);
        jScrollPane1.setViewportView(observer);

        
        MiseAJourCImage();
    }
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc=" Generated Code ">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new JScrollPane();


        setDefaultCloseOperation(WindowConstants.DISPOSE_ON_CLOSE);
        GroupLayout layout = new GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup())
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING))
                                .addContainerGap())
        )));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addGroup(layout.createSequentialGroup())
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE))
                                .addContainerGap())
        );
        pack();
    }// </editor-fold>//GEN-END:initComponents


    private void MiseAJourCImage()
    {
        double max = matrice[0][0];
        double min = matrice[0][0];
        for(int i=0 ; i<M ; i++)
            for(int j=0 ; j<N ; j++) {
                if (matrice[i][j] > max) max = matrice[i][j];
                if (matrice[i][j] < min ) min = matrice[i][j];
            }
        double blanc = max;
        double noir = min;
        int val;

        for(int i=0 ; i<M ; i++)
            for(int j=0 ; j<N ; j++)
            {
                if (matrice[i][j] >= blanc)
                {
                    matrice_int[i][j] = 255;
                }
                else
                {
                    if (matrice[i][j] <= noir)
                    {
                        matrice_int[i][j] = 0;
                    }
                    else
                    {
                        val = (int)((matrice[i][j] - noir)/(blanc-noir)*255+0.5);
                        if (val > 255) val = 255;
                        if (val < 0) val = 0;
                        matrice_int[i][j] = val;
                    }
                }
            }
        try 
        {
            image.setMatrice(matrice_int);
        } 
        catch (CImageNGException ex) 
        {
            System.out.println("Erreur CImageNG : " + ex.getMessage());
        }
    }
    

    
    /**
     * @param args the command line arguments
     */

    
    // Variables declaration - do not modify//GEN-BEGIN:variables

    private JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
    
}
